apiVersion: apps/v1
Kind: Deployment
metadata:
  name: ic-webapp
  namespace: ic-webapp
  labels:
    env: prod
    app: ic-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-webapp
  template:
    metadata:
      labels:
        app: ic-webapp
    spec:
      containers:
      - name: ic-webapp
        image: ic-webapp:latest
        env:
        - name: ODOO_URL
          value: http://172.28.128.32:30069/
        - name: PGADMIN_URL
          value: http://172.28.128.32:30050/
        ports:
        - containerPort: 8080
          name: ic-webapp

